### ISSUE TITLE
passende api's onderzoeken

### ISSUE THREAD

**Issue by altergith** [Compairifuel/Compairifuel#33]

**Comment by Mino03947** [comment]
Heb een candidaat gevonden voor een api: https://developer.tomtom.com/
het heeft alleen wel een limit van 50000 requests per dag. (dit zal later een probleem worden, maar voor project Compairifuel niet).

**Comment by Mino03947** [comment]
10min gespendeerd naar zoeken van een api.

**Comment by Mino03947** [comment]
Heb nog een canidaad gevonden voor een api: https://www.tankplanner.nl/api/v1/
Het mist alleen wel het één en ander aan informatie.

**Comment by Mino03947** [comment]
Heb nog een canidaat gevonden voor een api: https://opendata.cbs.nl/statline/#/CBS/nl/dataset/80416ned/tablets=1700480638167

Het geeft alleen wel de gemiddelde prijzen van Euro95, Diesel, Lpg van alle tankstations in nederland terug, dus je zou dit beter als default gebruiken. (is ook niet echt nodig in project Compairifuel)

**Comment by Mino03947** [comment]
20min gespendeerd aan het zoeken naar api's.

**Comment by altergith** [comment]
we hebben besloten om de Tom-tom api te gebruiker [Tom-Tom](https://developer.tomtom.com/)
